### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by NindoK** [thevikke/read_pdf_text#3]
Hi, 
With the latest updates, this plugin is not working anymore. 

`Android`
```
Running Gradle task 'assembleDebug'...
Note: /Users/mac/Development/flutter/.pub-cache/hosted/pub.dartlang.org/read_pdf_text-0.1.1/android/src/main/java/com/example/read_pdf_text/ReadPdfTextPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

`iOS`
```
CocoaPods' output:
↳
Error running pod install
Error launching application on iPhone 11 Pro Max.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

Finding Podfile changes
  A read_pdf_text
  - Flutter
  - path_provider
  - path_provider_linux
  - path_provider_macos
  - permission_handler
  - qr_code_scanner
  - receive_sharing_intent

Fetching external sources
-> Fetching podspec for `Flutter` from `Flutter`
-> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
-> Fetching podspec for `path_provider_linux` from `.symlinks/plugins/path_provider_linux/ios`
-> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`
-> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
-> Fetching podspec for `qr_code_scanner` from `.symlinks/plugins/qr_code_scanner/ios`
-> Fetching podspec for `read_pdf_text` from `.symlinks/plugins/read_pdf_text/ios`
-> Fetching podspec for `receive_sharing_intent` from `.symlinks/plugins/receive_sharing_intent/ios`

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_0_2_a.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/2/a/MTBBarcodeScanner/5.0.11/MTBBarcodeScanner.podspec.json exists! Returning local because checking is only perfomed in repo update
[!] CocoaPods could not find compatible versions for pod "read_pdf_text":
  In Podfile:
    read_pdf_text (from `.symlinks/plugins/read_pdf_text/ios`)

Specs satisfying the `read_pdf_text (from `.symlinks/plugins/read_pdf_text/ios`)` dependency were found, but they required a higher minimum deployment target.

/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Users/mac/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/Users/mac/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
/Users/mac/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/mac/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `eval'
/Users/mac/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `<main>'

Error output from CocoaPods:
↳

[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

I really would love this plugin to work, since is the only one which can extract text from the pdf and use it for my own purpoes.

Thanks

**Comment by thevikke** [comment]
Hello!

Do you mean that latest update to this plugin broke it or the latest flutter update?

**Comment by NindoK** [comment]
I honestly don't know. Just tried to use it now and I'm having problems!

I'm on stable by the way.
Thanks for the quick response

**Comment by thevikke** [comment]
Could you run flutter doctor -v and copy the output to here?

**Comment by NindoK** [comment]
```
flutter doctor -v
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.1 at /Users/mac/Development/flutter
    • Framework revision 2ae34518b8 (4 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android
      8.1.0 (API 27) (emulator)
```

**Comment by thevikke** [comment]
Okay, thank you! I think I can replicate the error at least on Android. I will investigate what is causing it.

**Comment by thevikke** [comment]
I tested the Android version and got it working.
The error in there was related to file permissions and I solved it by running Visual studio as an administrator.

I will now check the Mac version.

**Comment by thevikke** [comment]
The package is working for me on Mac with Flutter-stable build.
For me it complained about the Podfile, so I ran:` rm ios/Podfile ` after this I received no other problems.

**Comment by NindoK** [comment]
Yes, worked for me too! Thanks man :)
